### ISSUE TITLE
Action 'edit' isn't available on class GridFieldSubsiteDetailForm_ItemRequest.

### ISSUE THREAD

**Issue by AlphaCactus** [silverstripe/silverstripe-subsites#103]
After latest update, this occurs when attempting to create a new subsite.

```
Action 'edit' isn't available on class GridFieldSubsiteDetailForm_ItemRequest.
```

So I added 

```
class GridFieldDetailForm_ItemRequest extends RequestHandler {
    private static $allowed_actions = array( 'edit' );
...
}
```

which then allowed me to create a subsite.
Then when I tried to click save to a domain to the subsite I get.

```
Action 'ItemEditForm' isn't available on class GridFieldDetailForm_ItemRequest.
```

So I added 

```
class GridFieldDetailForm_ItemRequest extends RequestHandler {
    private static $allowed_actions = array( 'ItemEditForm', 'edit' );
...
}
```

I must flush between each change to allowed_actions.
And with GridFieldDetailForm_ItemRequest thusly hacked it works.
Using latest 3.1 master branch of framework and cms.

**Comment by robbieaverill** [comment]
Closing as this is surely fixed since 2013. If it's still a problem feel free to reopen! Thanks
