### ISSUE TITLE
BUG init() not called on pages referenced by SubsitesVirtualPage 

### ISSUE THREAD

**Issue by moveforward** [silverstripe/silverstripe-subsites#109]
When a SubsitesVirtualPage is added and viewed, the SubsitesVirtualPage_Controller init() method only fires the init() method of it's parent (VirtualPage_Controller). The init method of the referenced controller is not fired - so no initialisation code for the referenced page controller is fired either

**Comment by robbieaverill** [comment]
This should be fixed with https://github.com/silverstripe/silverstripe-cms/issues/1386 and https://github.com/silverstripe/silverstripe-cms/pull/1605
