### ISSUE TITLE
Copying pages from main site produces history error before publish

### ISSUE THREAD

**Issue by mandrew** [silverstripe/silverstripe-subsites#119]
It looks like a history entry isn't created until a copied page is published so an error is returned in the CMS when you click on the history tab.

Note: this doesn't happen when creating a new page directly in the subsite.

Replicate:
 * Copy any main site page to a subsite by choosing the page, and then choose the subsite from the 'Copy page to subsite' dropdown on the page.
 * Press the 'Copy' button and then visit the 'History' tab on the new page in the subsite

The following error should appear:
Failed to load resource: the server responded with a status of 500 (Notice at line 1231 of /Users/mandrew/Sites/recipe-basic/framework/model/Versioned.php) http://localhost/recipe-basic/admin/pages/history/show/122?locale=en_NZ&locale=en_NZ

**Comment by tractorcow** [comment]
Seems fixed. :D
