### ISSUE TITLE
SS 3.1.2 Subsite::duplicate() & SiteTreeSubsites::duplicateToSubsite()

### ISSUE THREAD

**Issue by jakxnz** [silverstripe/silverstripe-subsites#134]
These methods don't seem to be writing the duplicate pages to the database correctly. Duplicates end up created incomplete records which show up in the main site instead of duplicating to new or existing subsites.

**Comment by chasevida** [comment]
Nice to see that a year on this problem is still happening. Any solutions since you both posted a year ago?

**Comment by chasevida** [comment]
Ok, so for anyone else coming here with this issue, there is a way to get this working but before that I'd make a suggestion that you give up on this cms framework. If you can't do that then it's mentioned in the [source here](https://github.com/silverstripe/silverstripe-subsites/blob/1.0/code/tasks/SubsiteCopyPagesTask.php) that you can run the following task via the `sake` cli tool.

`sake dev/tasks/SubsiteCopyPagesTask from=<subsite-template-id> to=<subsite-target-id>`

You will need the `id` of the subsite you are copying from and the `id` of the subsite you are copying too. So they both need to exist before hand.

**Comment by chasevida** [comment]
Well a little further on I've just realised this doesn't copy any `SubsitesVirtualPage` types across. It copies the page directly making a direct copy appending an index number to the page url. Great if your wanting straight copies of everything, not so great if you expected your page types to be copied verbatim.

**Comment by robbieaverill** [comment]
@jakxnz @Estr3a2 @chasevida are you still experiencing this issue in the more recent versions of subsites?

**Comment by chasevida** [comment]
Wouldn't know as I no longer use SilverStripe.
