### ISSUE TITLE
summaryfields not extendable using DataExtension

### ISSUE THREAD

**Issue by cloph** [silverstripe/silverstripe-subsites#137]
It's impossible to extend Subsite's summary view with custom fields added using a DataExtension since it misses a hook to extend via UpdateSummaryField an doesn't look at $summary_fields either.

**Comment by robbieaverill** [comment]
Looks like this change got reverted or overridden at some point, labelled as a bug

**Comment by robbieaverill** [comment]
I can't reproduce this on SilverStripe 4.4 with Subsites 2.3.x-dev:

```yaml
# File: app/_config/temp.yml
SilverStripe\Subsites\Model\Subsite:
  summary_fields:
    - DefaultSite.Nice
```

![image](https://user-images.githubusercontent.com/5170590/58672186-cf242c00-8399-11e9-82f4-fbeecb8e27f4.png)
