### ISSUE TITLE
Redirect loop on missing 404 error page on subsites

### ISSUE THREAD

**Issue by SebastianMucke** [silverstripe/silverstripe-subsites#140]
If one is calling a non-existent url on a subpage (f.e. http://sub.domain.com/Missing), SilverStripe forwards the request to root (http://sub.domain.com/). This is not existing on subsites, too so SilverStripe redirects again to http://sub.domain.com/ meaning an infite redirection loop.

Creating a new ErrorPage for 404 on my subsite fixed the problem.

In the case, there is no 404 error page on the subsite, the user should be forwarded to  the 404 error page of the main site or at least get an ugly plain 404 error.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
