### ISSUE TITLE
BUG Behat subsite selector issue

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-subsites#147]
There seems to be an issue with behat tests using the dropdown field. This has become an issue since upgrading to mink 1.6, which is a lot more strict on interacting with hidden elements. Specifically, the use of chosen dropdown is interfering with behat / subsites.

using the below .feature adjustment will make the dropdown change value but doesn't seem to trigger the redirect.

``` yml
And I select "My subsite" from "SubsitesSelect" with javascript
```

**Comment by robbieaverill** [comment]
@tractorcow the existing "Preview navigation" feature looks like it covers this behaviour (2.3.x), so I'm going to close this. Feel free to reopen if I've misunderstood and it's still a problem!
