### ISSUE TITLE
SubsiteDomain should ignore port

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe/silverstripe-subsites#159]
When developing with a vagrant vm the port of the current VM may be different.

Subsites::getSubsiteIDForDomain calls $_SERVER['HTTP_HOST'] which may be localhost:8080

Wouldn't be $_SERVER['SERVER_NAME'] not better?

maybe make this switchable by a $ignore_port config and decide what to call.

**Comment by robbieaverill** [comment]
@wernerkrauss would you be willing to submit a pull request for this?
