### ISSUE TITLE
Main site pages being shown in subsite

### ISSUE THREAD

**Issue by matt-bailey** [silverstripe/silverstripe-subsites#161]
I'm trying to set up the subsites module but I'm struggling to get it working correctly.

Basically when I set up a subsite it shows the main site's content. When I add a page to the subsite (`http://subsite.main-domain.dev/test-page` for example) and then try to access it in the browser I get a redirect loop.

No doubt it's something to do with my local dev environment set up, but I'm not sure what?

I'm developing in a Vagrant box (Ubuntu). My server name is set to `playbook.dev` and I have two aliases set up, `playbook.dev` and `test.playbook.dev`.

On my host machine (OS X), in the hosts file I also have two hosts set up:

```
192.168.56.103 playbook.dev
192.168.56.103 test.playbook.dev
```

This is what the subsite admin page looks like:

![Silverstripe Subsites](http://f.cl.ly/items/3I0P022u1t3e320E1B0A/Silverstripe%20Subsites.png)

Can anyone help, thanks?

**Comment by michalkleiner** [comment]
I believe each subsite needs a default home page (a page with URLSegment = 'home') to prevent the redirects. Unfortunately, a default home page is not created when a subsite is created.

**Comment by michalkleiner** [comment]
You probably moved on since the issue was created, so could be good to update it if it's still a problem or it can be closed. Cheers.
