### ISSUE TITLE
Errors on /dev/build

### ISSUE THREAD

**Issue by theade** [silverstripe/silverstripe-subsites#162]
Strict Standards: Declaration of SiteTreeSubsites::augmentSQL() should be compatible with DataExtension::augmentSQL(SQLQuery &$query) in /Users/username/Documents/Work/Current/Workspace/SiteName/subsites/code/extensions/SiteTreeSubsites.php on line 296

Strict Standards: Declaration of GroupSubsites::augmentSQL() should be compatible with DataExtension::augmentSQL(SQLQuery &$query) in /Users/username/Documents/Work/Current/Workspace/SiteName/subsites/code/extensions/GroupSubsites.php on line 7

I'm getting the following on the latest SS and on 3.1.0 rc3. Am I doing something wrong?

Cheers

Strict Standards: Declaration of FileSubsites::augmentSQL() should be compatible with DataExtension::augmentSQL(SQLQuery &$query) in /Users/username/Documents/Work/Current/Workspace/SiteName/subsites/code/extensions/FileSubsites.php on line 128

Strict Standards: Declaration of SiteConfigSubsites::augmentSQL() should be compatible with DataExtension::augmentSQL(SQLQuery &$query) in /Users/username/Documents/Work/Current/Workspace/SiteName/subsites/code/extensions/SiteConfigSubsites.php on line 49

Fatal error: Call to undefined method SQLQuery::getWhereParameterised() in /Users/username/Documents/Work/Current/Workspace/SiteName/subsites/code/extensions/SiteConfigSubsites.php on line 21

**Comment by bigbang1980** [comment]
I have This one :(
Fatal error: Call to undefined method SQLQuery::getWhereParameterised() in /Users/username/Documents/Work/Current/Workspace/SiteName/subsites/code/extensions/SiteConfigSubsites.php on line 21

**Comment by kinglozzer** [comment]
@bigbang1980 As above, you’re using the wrong version of subsites. If you’re using composer, specify version "~1.0.0". If you’re not using composer, download the zip from this branch instead of master: https://github.com/silverstripe/silverstripe-subsites/tree/1.0
