### ISSUE TITLE
BetterButtons and Subsites backlink issue

### ISSUE THREAD

**Issue by spekulatius** [silverstripe/silverstripe-subsites#165]
I am not entirely sure this issue is in the right place here. In a project I am using BetterButtons and Subsites. In the subsites section the 'Save' Button works fine but the 'Save and Close' button redirects to the 'show' action which doesn't exist for the subsites. I checked the BetterButtons code and found out that a function returning the backlink fixes it:

```
/**
 * returns the target for the redirect of the BetterButtons 'Save and Close'-Button
 *
 * @return string
 **/
public function Backlink() {
    return 'admin/subsites';
}
```

I am not entirely sure this should be done here or adjusted via BetterButtons. Did someone has the same issue? Is there a better way to fix this?

**Comment by robbieaverill** [comment]
Thanks for reporting @spekulatius. Since this appears to be a problem with betterbuttons I suggest you raise an issue with that module.
