### ISSUE TITLE
Use config.yml

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-subsites#174]
Is there a reason subsites doesn't make use of the Config class?

I just spent a couple of hours trying to work out why my files were getting a SubsiteID applied, then I realised that FileSubsites::$default_root_folders_global can not be set in a yml file. Doh!

**Comment by dhensby** [comment]
sounds like it needs a serious upgrade!

**Comment by michalkleiner** [comment]
+1

**Comment by robbieaverill** [comment]
Pull request at https://github.com/silverstripe/silverstripe-subsites/pull/335
