### ISSUE TITLE
Installing by composer cause an error

### ISSUE THREAD

**Issue by Slavka** [silverstripe/silverstripe-subsites#175]
There is no "silverstripe/framework 3.2" package available.
Here is 
composer require "silverstripe/subsites"
trace:

Using version ~1.1@dev for silverstripe/subsites
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - silverstripe/cms 3.x-dev requires silverstripe/framework 3.2.x-dev -> no matching package found.
    - silverstripe/subsites 1.1.x-dev requires silverstripe/cms ~3.2 -> satisfiable by silverstripe/cms[3.x-dev].
    - Installation request for silverstripe/subsites ~1.1@dev -> satisfiable by silverstripe/subsites[1.1.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by alicetragedy** [comment]
Hi @Slavka, I had a similar problem, and I had to install a previous version. Maybe try
`composer require silverstripe/subsites 1.0.5`
it worked for me... :)
