### ISSUE TITLE
Allow adding Google Analytics code to subsite via CMS

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-subsites#18]
Moved from http://open.silverstripe.org/ticket/4047

It would be good if admins could add GA code for a subsite directly through the CMS instead of having to ask a developer to add it to the template. This would give them a lot more flexibility in setting up a subsite end-to-end.

**Comment by wernerkrauss** [comment]
Isnt' this possible now, as each Subsite has it's own SiteConfig Object in DB?

**Comment by wilr** [comment]
Yep, easy to extend via `SiteConfig` like any other field now.
