### ISSUE TITLE
Subsite Virtual Page bugs

### ISSUE THREAD

**Issue by extravio** [silverstripe/silverstripe-subsites#185]
We're experiencing problems with the "Subsite Virtual Page" provided by the Subsites module:
- When creating / editing a page, it is not possible to select a different subsite. After saving it always revert back to the previous subsite.
- The Linked Page sitetree doesn't refresh when selecting a different subsite
- Also, the controller that returns the site tree always seems to return the same subsite sitetree, ignoring the SubsiteID parameters
  ( url http://mydomain.com/admin/pages/edit/EditForm/field/CopyContentFromID/tree?CopyContentFromID_SubsiteID=2 [^] <- returns same as 0 or 1
- In some cases, the main Page template is not picked up and the content is displayed in a "blank" template.

**Comment by wernerkrauss** [comment]
Possible fix for the subsites tree dropdown: https://github.com/dnadesign/silverstripe-subsites/commit/d0956d4b86b229f05da7ae73313af01d0f8023d6

**Comment by robbieaverill** [comment]
I'm looking at this now with SilverStripe 4.4 and Subsites 2.3. Here's my notes:

> When creating / editing a page, it is not possible to select a different subsite. After saving it always revert back to the previous subsite.

I can't reproduce this any more, it works for me. I did run into #423 with fluent installed as well, which has a PR attached.

> The Linked Page sitetree doesn't refresh when selecting a different subsite

This works in SilverStripe 4.x

> Also, the controller that returns the site tree always seems to return the same subsite sitetree, ignoring the SubsiteID parameters
( url http://mydomain.com/admin/pages/edit/EditForm/field/CopyContentFromID/tree?CopyContentFromID_SubsiteID=2 [^] <- returns same as 0 or 1

Cannot reproduce

> In some cases, the main Page template is not picked up and the content is displayed in a "blank" template.

I couldn't reproduce this when I tested it in #276
