### ISSUE TITLE
Keeps subsite tree after changing site from the dropdown site picker

### ISSUE THREAD

**Issue by iamyellow** [silverstripe/silverstripe-subsites#186]
Hi, 1st of all thanks for your work!
I think I've detected some bug, if you want to reproduce:
- go to Pages and edit a page
- change site from the left dropdown site picker
- go to Pages, you'll see the previous site tree.

that not happens if you change the site and you're not editing a page.

Using SS 3.1, updated w/ composer a couple of days ago...

Hope it helps!

**Comment by thezenmonkey** [comment]
Yes, it seems you can only change subsites from root Pages tab. If you're editing a page changing the subsite returns you to the root pages interface for the subsite you're currently editing.

**Comment by robbieaverill** [comment]
Thanks for reporting. I can't reproduce this any longer on SS 3.6.0, so assume it's been fixed.
