### ISSUE TITLE
SubsiteID: Replace session state with request state (support multiple tabs)

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-subsites#19]
Moved from http://open.silverstripe.org/ticket/4224

Issue description:

Open the CMS in one browser tab and go to a subsite
Open another browser tab and load the main site (public view - not the CMS)
Now when you try to insert a link on the subsite, the site tree shows the main site instead of the subsite.
Desired behaviour:

The site tree should always be populated based on the currently open site in the CMS.
This may be related to ticket http://open.silverstripe.org/ticket/4012

**Comment by robbieaverill** [comment]
@halkyon is it still an issue 😄

**Comment by robbieaverill** [comment]
This is duplicated by #314, but I'm going to close this in favour of that because there is more discussion on that ticket
