### ISSUE TITLE
Subsite Virtual Page URLSegment Iterator Issue

### ISSUE THREAD

**Issue by thezenmonkey** [silverstripe/silverstripe-subsites#193]
Making changes to a page triggers the duplicate URLSegment itarator to trigger on any VirtualPages pointing to it.

For istance if I change a page with the URL Segment my-page all it's subsite virtual pages become my-page-2

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-subsites/pull/247
