### ISSUE TITLE
Incomplete SubsiteXHRController canAccess() method

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-subsites#200]
On a fresh install of silverstripe + framework 3.1.3 / PHP5.5.9 / Ubuntu 14.04 LTS / Firefox.<excessively_large_version_number>

I can confirm the following in v1.0.8 and dev-master (The latter only by reviewing the logic) and in a setup with __no configured subsites__.

Logging into the CMS as a user with the following permissions, results in "403 Forbidden" errors showing in the CMS' "Growl" error box in the top-right when visiting various CMS admin areas, yet access is still granted to them regardless.

* Login as an ADMIN
* Create group "TEST"
* Permissions on _all_ CMS admin screens 
* Permission to Edit & View pages
* Create new user and add them to the "TEST" group
* Logout
* Login as user just created
* Navigate to arbitrary CMS admins and observe Growl error
* Using browser dev-tools observe error derives from `SubsiteXHRController`

`SubsiteXHRController::canAccess()` assumes the CMS' AJAX logic will deal with no return from `canAccess()` in the case where there are __no configured subsites__ in the system. This results in a default "return value" of null resulting in the 403.

`canAccess()` appears incomplete. What it's saying is "Allow access" to a subsite if you have any subsites configured. But if there are no subsites configured, should `canAccess()` even be called?

**Comment by dhensby** [comment]
I can confirm I've replicated this error on framework//cms 3.1.x-dev and 1.0.x-dev of susbsites.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-subsites/pull/249
