### ISSUE TITLE
CMS requests to SubsiteXHRController fail with 404.

### ISSUE THREAD

**Issue by bummzack** [silverstripe/silverstripe-subsites#203]
I'm using `1.1.x-dev` and SilverStripe 3.2.
Navigating the CMS triggers requests to `SubsiteXHRController` which all fail with a 404.

As much as I can tell, these are triggered via JavaScript from `LeftAndMain_Subsites.js`. I think there's a route that's missing in a config file?

Adding something like this makes the problem go away:
```
Director:
  rules:
    'SubsiteXHRController': 'SubsiteXHRController'
```

Not sure if that wasn't required prior to 3.2, because on a first glance I wasn't able to find the route in previous versions?

**Comment by wernerkrauss** [comment]
Hi bummzack, good point, afaik the auto route to the controller with the same name felt away in SS3.2. See Changelog: https://docs.silverstripe.org/en/3.2/changelogs/3.2.0/#api-removed-url-routing-by-controller-name

So i guess a PR will be welcome ;)

**Comment by bummzack** [comment]
@wernerkrauss Ah, ok then that's the reason. Time to read these changelogs and create a PR ;)

**Comment by wernerkrauss** [comment]
Can you please double check for other missing routes?

**Comment by bummzack** [comment]
@wernerkrauss I did. Couldn't find any though.

**Comment by dhensby** [comment]
I believe this is fixed - please let me know if not
