### ISSUE TITLE
Copy to Subsite Action Button Missing

### ISSUE THREAD

**Issue by pbnj4640** [silverstripe/silverstripe-subsites#205]
The button that initiates the copying of a page from one subsite to another is not longer visable on SS3.2 using build 1.1.
![capture](https://cloud.githubusercontent.com/assets/8837574/10831619/1e6e9e4e-7e5d-11e5-8eed-e3b142615bd7.PNG)

**Comment by tractorcow** [comment]
This has been fixed in https://github.com/silverstripe/silverstripe-framework/pull/4717
