### ISSUE TITLE
Saving translations on main-site fails due to "Copy page to subsite"

### ISSUE THREAD

**Issue by NoLdman** [silverstripe/silverstripe-subsites#223]
Translations created by *silverstripe/silverstripe-translatable* can't be saved if using the main-site, because the "Copy page to subsite" drop-down is always `(empty)`.

It throws the following error during saving: "Please select a value within the list provided. is not a valid option".

**Comment by tractorcow** [comment]
I guess this is in 3.2? This seems to be an issue in the dropdown API where validation fails if the list is empty.

**Comment by tractorcow** [comment]
Moved to https://github.com/silverstripe/silverstripe-framework/issues/4849 since this is a framework bug. ;)

**Comment by NoLdman** [comment]
Sorry, forgot to mention: Yes it was framework v3.2 silverstripe/silverstripe-framework@0178fa5a1873a0f1d6100268c86dab81a18c23a5 with the latest 1.* subsites-module silverstripe/silverstripe-subsites@b4024c94bb1dd4d404c4aa2fd22e5f0cbedbc7eb
