### ISSUE TITLE
Unable to pickup theme

### ISSUE THREAD

**Issue by ctx2002** [silverstripe/silverstripe-subsites#228]
Hi:

I have just installed Silverstripe 3.2 and subsite 1.2.0,
I have tried to create a new subsite, but Theme dropdown menu contains nothing.
so I am unable to create a sub site.

**Comment by ctx2002** [comment]
Ok, I have found out why.

File, /home/vagrant/www/silverstripe/dgc2/subsites/code/model/Subsite.php contains a function to get all themes.

but My theme location is /home/vagrant/www/silverstripe/dgc2/theme.

So I have changed public function allowedThemes()
    {
        
        if ($themes = $this->stat('allowed_themes')) {
            return ArrayLib::valuekey($themes);
        } else {
            $themes = array();
            $d = dirname(dirname(dirname(dirname(__FILE__))));
            //if (is_dir('../themes/')) {
            if (is_dir($d.'/themes/')) {
                //var_dump("hello"); die();
                //foreach (scandir('../themes/') as $theme) {
                foreach (scandir($d.'/themes/') as $theme) {
                    if ($theme[0] == '.') {
                        continue;
                    }
                    $theme = strtok($theme, '_');

                    $themes[$theme] = $theme;
                }
                ksort($themes);
            }
            return $themes;
        }
    }

I still do not understand why module author use is('../themes') to scan theme, my theme folders is 3 levels up.

**Comment by tractorcow** [comment]
is `/home/vagrant/www/` your web-root, and `http://localhost/silverstripe/dgc2` your base url?

**Comment by ctx2002** [comment]
my web server is nginx, web root is , /home/vagrant/www/silverstripe/dgc2
my base url is dcg2.app:8000

**Comment by tractorcow** [comment]
Oh, I see.

Try changing your themes folder to `themes` instead of `theme`? You need to use the standard paths, as the actual themes folder isn't customisable. Your theme will also need to be a named subfolder beneath this.

See https://docs.silverstripe.org/en/3.2/developer_guides/templates/themes/ for docs reference.

**Comment by ctx2002** [comment]
My theme is "themes", I will edit my original folder. this is a fresh installation of Silverstripe , so I did not change any thing

**Comment by tractorcow** [comment]
Themes path should be set via the constant `THEMES_PATH`. Try substituting that?

**Comment by ctx2002** [comment]
nice, so changed following 2 lines, now it works.

if (is_dir('../themes/')) to if (is_dir(THEMES_PATH))

foreach (scandir('../themes/') as $theme) to foreach (scandir(THEMES_PATH) as $theme)

**Comment by tractorcow** [comment]
Excellent.

Do you want to make a pull request so we can get this fix into the module too? :D

**Comment by tractorcow** [comment]
Pull to 1.2 branch. :)

**Comment by ctx2002** [comment]
I have downloaded version 1.2.0 which is not a dev version, probably not suitable for a pull request.
By the way, how to notify subsite module core developer about this bug?

**Comment by tractorcow** [comment]
You've already done this... that's me. :D

You can just go to the 1.2 branch and create a pull request in the github editor if you like.

**Comment by tractorcow** [comment]
Check out https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

**Comment by ctx2002** [comment]
I have created pull request, thanks for the instructions.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-subsites/pull/229
