### ISSUE TITLE
subsite and SiteConfig module -- Theme not been updated

### ISSUE THREAD

**Issue by ctx2002** [silverstripe/silverstripe-subsites#231]
It seems, SiteConfig module does not aware of Subsite module's theme choice.

My site has 2 themes, one is simple, one is bootstrap. 
At beginning  , my Subsite has "simple" as theme, Then I did changed my subsite to bootstrap theme,
the subsite was loading simple still.

After  hours searching/debuging, I have found out that , in table "SiteConfig", my subsite's Theme field is "simple". If I chang the field content to "bootstrap", then my subsite picks up bootstrap.

There must has some code do update "Theme" field of SiteConfig table, but I am unable to find the code.

my Silverstripe is 3.2.1, "silverstripe/siteconfig" is "3.2.1".

**Comment by ctx2002** [comment]
right, I know why now.

There are 2 places to update subsite theme.

the first one is , when click on "subsite", then click on subsite entry on right hand screen. a "Theme" dropdown menu will be displayed. if I change theme use this dropdown menu, no effect.

the second one is. when choose a subsite on left - top corner, then click on "Setting" , and choose a theme, now subsite's theme saved into DB.

This is very confusion, why subsite provides it own theme selection.

**Comment by tractorcow** [comment]
I think the theme should be set only in siteconfig; Subsites have multiple siteconfigs for each subsite, so you can still set a different theme for each.

Shall we ditch the Subsite.Theme field?

**Comment by ctx2002** [comment]
Yes, I think so. we should ditch the Subsite, theme field.

**Comment by robbieaverill** [comment]
Related #273

**Comment by robbieaverill** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

---

Related issue for SilverStripe 4 with cascading themes: #392
