### ISSUE TITLE
SubsiteDomain::getSubstitutedDomain does not returns port

### ISSUE THREAD

**Issue by ctx2002** [silverstripe/silverstripe-subsites#233]
SubsiteDomain::getSubstitutedDomain does not returns url "port" number:

so we have to added following code:

1> $port = parse_url($currentHost, PHP_URL_PORT);
2> if ($port !==FALSE && $port != 80) {
            $domain .= ":".$port;
        }

please have a look.

I can make a pull request , if you want.

**Comment by tractorcow** [comment]
Can you explain why this method should return a port number? It appears that it returns exactly what it promises, the domain name. The port is not a part of the domain.

If you need a custom port, I suggest subclassing SubsiteDomain for your needs, perhaps putting it into a separate field, then overriding getAbsoluteLink().

```php

public function getAbsoluteLink() {
	$link = parent::getAbsoluteLink:()
	if($this->Port) {
		return $link . ":" . $this->Port;
	}
	return $link;
```

Or something like that.

**Comment by ctx2002** [comment]
the reason is, Our code use Subsite::absoluteBaseURL() which calls SubsiteDomain::getSubstitutedDomain().

So I am unable to subclass SubsiteDomain in this case, since our code not directly use SubsiteDomain. 
how about change Subsite::absoluteBaseURL that returns a port number?

**Comment by ctx2002** [comment]
ok, I will do this in our code.
Subsite need to add a getAbsoluteLink method. so it returns a uri with port number
