### ISSUE TITLE
Subsite Virtual Page will error if referenced page is unpublished

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-subsites#236]
If you Sync files, or any other action that will re validate the site tree, the following error will be thrown:

`Validation error: Page type "Page" not allowed as child of this parent page`

Not only is this error inaccurate, but going back deleting the subsite virtual pages in question is laborious.

**Comment by tractorcow** [comment]
Do you know what part of files sync causes a sitetree re-validation?

Do you have a page as a child of the virtual page, or of the page linked to by the virtual page?

**Comment by robbieaverill** [comment]
Closing due to lack of feedback. @torleif please feel free to reopen if you're still experiencing this problem, with some extra detail to reproduce.

**Comment by robbieaverill** [comment]
For what it's worth, I can't reproduce this issue on SilverStripe 4.x (subsites 2.3) now anyway
