### ISSUE TITLE
Subsite Friendly URLs 

### ISSUE THREAD

**Issue by hudhaifas** [silverstripe/silverstripe-subsites#240]
I have setup couple of subsites, but I would like to use a clean URL without SubsiteID parameter, even when I assign a subdomain for the sub site it just redirects and use the SubsiteID, is there a way to use sub-directories structure instead?

I need:
www.mydomain.com/subsite1/home
www.mydomain.com/subsite1/about
www.mydomain.com/subsite2/about
www.localhost/subsite2/contact

or 
www.subsite1.mydomain.com/home
www.subsite1.mydomain.com/about
www.subsite2.mydomain.com/about

instead of
www.mydomain.com/home?SubsiteID=1
www.mydomain.com/about?SubsiteID=1
www.mydomain.com/about?SubsiteID=2
www.localhost/contact?SubsiteID=2

**Comment by dhensby** [comment]
Have you followed the [instructions](https://github.com/silverstripe/silverstripe-subsites#installation) ?

**Comment by hudhaifas** [comment]
Hi Daniel,

Maybe I have a problem in the last point - updating the DNS! but in Godaddy I have created a subdomain points to the main site and used the same subdomain in the subsite domain, but same problem!

Do I misunderstand the tutorial?

**Comment by dhensby** [comment]
Have you done this bit specifically:

> Once you've created a subsite, you'll see a "Create Subsite Domain" button, hit that button to enter a domain or subdomain for your subsite. This will determine the URL of your website. For example, if your site is running on http://localhost/mysite, and you set the subdomain to "subsite", then your subsite will be accessible on http://subsite.localhost/mysite

**Comment by dhensby** [comment]
Also, these types of questions should go on the [forum](http://www.silverstripe.org/community/forums) or [stackoverflow](http://stackoverflow.com/questions/tagged/silverstripe) as we only use the GitHub issues for bugs.

**Comment by hudhaifas** [comment]
Thank you for the support! I am able to handle it, the problem was in the Create Subsite Domain, I was entering the subdomain only! ("subsite" instead of "subsite.mydomain.com/mysite"). It works now.

**Comment by dhensby** [comment]
Great
