### ISSUE TITLE
Can not access SubSites by domain if they are locked to logged in users

### ISSUE THREAD

**Issue by jakedaleweb** [silverstripe/silverstripe-subsites#243]
If a SubSite has a domain and has its access limited to logged in users, it can not be accessed by that domain even if a user is logged in.

The request to the domain gets redirected to /login, which has to use the default CWP domain to ensure an https connection. Once at login if you are already logged in you will re redirected to the base domain and therefore not at the desired subsite.
 
![screen shot 2016-04-07 at 11 59 30 am](https://cloud.githubusercontent.com/assets/11186642/14336555/454561da-fcb9-11e5-99f3-3bda54df3cba.jpg)

?SubsiteID still works to access the subsite.

**Comment by tractorcow** [comment]
This sounds like a CWP issue, not a subsite one. Being redirected to the base domain is a setting you can (and will need to) disable for this site.

You probably need to set `CwpControllerExtension.ssl_redirection_force_domain` to false. Is that the case in your site?

You can't login in one domain (or even across protocols) and have the session shared, as cookies are specific to each domain / protocol. You need to login on that subsite in order for your login to be respected.

**Comment by prij** [comment]
@tractorcow I agree that this is likely a CWP issue because I can't replicate locally.
I only have the default config set, so `CwpControllerExtension.ssl_redirection_force_domain `is not false.

I suspect setting it to false will resolve the issue - is this a recommended CWP setting?

**Comment by tractorcow** [comment]
It's only recommended if you are using front-end authentication.

See https://www.cwp.govt.nz/developer-docs/en/1.3/working_with_projects/security/#front-end-authentication-2 for the offical CWP docs on this.
