### ISSUE TITLE
CMS Issue when using Subsite subdomains with SSL

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-subsites#245]
The CMS has been hanging for me when using the Preview pane, and I believe it's due to a compatibility issue between Subsite subdomains and SSL:

![](http://spdr.me/1bGTN+)

**Comment by tractorcow** [comment]
We could possibly re-implement this behaviour with postMessage, which allows iframes to communicate with their parent behaviour.

We have a `$(window).on("message", function(e) {});` in LeftAndMain.js we can probably use as an entry point.

By the way, which framework version are you using? I want to track that exact stacktrace. :)

**Comment by purplespider** [comment]
I believe the above trace was from version 3.2.1.

**Comment by mikenz** [comment]
https://github.com/silverstripe/silverstripe-framework/pull/5163 was the fix for this in 4. It might guide you towards a solution for 3.2

**Comment by robbieaverill** [comment]
According to silverstripe/silverstripe-framework#5684 this should be fixed in SS 3.3 and above. Feel free to reopen if this isn't the case!
