### ISSUE TITLE
"Protocol" in subsite domain editor should have a default value

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-subsites#251]
![image](https://cloud.githubusercontent.com/assets/111025/15994104/0539847a-314f-11e6-8bcc-d98a9829ff7e.png)

**Comment by robbieaverill** [comment]
Still an issue in SS4

**Comment by robbieaverill** [comment]
Let's just call this a bug =D

**Comment by robbieaverill** [comment]
PR to fix this and a duplicate description bug here https://github.com/silverstripe/silverstripe-subsites/pull/417.

Duplicate description issue:
![image](https://user-images.githubusercontent.com/5170590/58667095-3685b000-8389-11e9-8bda-313bf24f51f0.png)
