### ISSUE TITLE
New subsite should automatically get a "home" page (infinite redirects otherwise)

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-subsites#252]
Every SilverStripe website needs a page with the `home` URLSegment. Creating an empty subsite leads to infinite redirects when not copying structure from a template. This is hardly ideal default behaviour.

**Comment by tractorcow** [comment]
I suggest that default behaviour should be to redirect to the first page in the subsite, if a page with `home` isn't present.

**Comment by sanderha** [comment]
+1 one to this. I was quite confused when setting up this module for the first time and getting infinite redirects.

**Comment by robbieaverill** [comment]
Do we want to simply add some logic to add a home page to the subsite when it's created after checking it has no pages in it already?

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-subsites/pull/359 for SS3 with example for merging up to SS4

**Comment by robbieaverill** [comment]
Merged up and releases with 1.4.1 (SS3) and 2.0.2 (SS4)
