### ISSUE TITLE
If you're an admin of a subsite group, you become a global admin

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-subsites#258]
Assigning a user a group that has admin access to a single subsite will cause the user to gain admin access to the whole site.

It's also very confusing, you have to load the subsite in question to see the role being assigned to the user.

**Comment by robbieaverill** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
