### ISSUE TITLE
Subsites with Fluent module

### ISSUE THREAD

**Issue by hudhaifas** [silverstripe/silverstripe-subsites#267]
How can I configure Subsites and Fluent modules in order to have a set of different locales for each subsite, example:
**Main Site**
  - en 
  - de

**Subsite 1**
  - en
  - fr

**Subsite 2**
  - es
  - pt

**Comment by tractorcow** [comment]
You could set up a separate domain in fluent, where each subsite matches one domain, and have your groups of locales match the domains you want to group with.

https://github.com/tractorcow/silverstripe-fluent/blob/master/docs/en/domain-configuration.md

My advice is try to avoid subsites with fluent if you can help it. :)

**Comment by robbieaverill** [comment]
Hi @hudhaifas - does the reply above resolve your question? Feel free to reopen the issue if you have more problems.

**Comment by aetchell** [comment]
> You could set up a separate domain in fluent, where each subsite matches one domain, and have your groups of locales match the domains you want to group with.
> 
> https://github.com/tractorcow/silverstripe-fluent/blob/master/docs/en/domain-configuration.md
> 
> My advice is try to avoid subsites with fluent if you can help it. :)

Is this still the case, and if so, how come they are generally offered together as part of the default  CWP config?

**Comment by tractorcow** [comment]
CWP has too many features. It really should be "here are two options, pick one or neither" :)

Subsites is good if you want multi-sites but not localisation.

Fluent is better if you want localisation.

**Comment by robbieaverill** [comment]
Yes- they are offered together with CWP as a suite of options for which you can choose what you want. I’d expect CWP users to trim down the feature set when they don’t need everything.

**Comment by NightJar** [comment]
CWP is not a multi host solution - The mini stack was created around the need for this, and might fill requirements better for such cases where subsites is often misused. https://www.cwp.govt.nz/plans/

**Comment by Leapfrognz** [comment]
> CWP has too many features. It really should be "here are two options, pick one or neither" :)
> 
> Subsites is good if you want multi-sites but not localisation.
> 
> Fluent is better if you want localisation.

What if you want multi-sites _and_ localisation?

**Comment by robbieaverill** [comment]
@Leapfrognz I would suggest using fluent in that case. You can achieve the same "multi site" structure with fluent (including separate domains), but you won't have all of the features that subsites offers such as permission separation, etc.

**Comment by Leapfrognz** [comment]
Yep we need those features. Plus this is an existing site. What are the issues we need to look out for? Are they documented anywhere? Are there any workarounds for these fixes?

**Comment by robbieaverill** [comment]
@Leapfrognz if you need the features that both modules offers, you are more than welcome to use them together. They should generally behave well together, but there will be duplication of effort - e.g. two ways of filtering a site tree when subsites and fluent both do it their own way. It's worth noting that this issue was raised some time ago, the landscape of both modules has changed considerably since then.
