### ISSUE TITLE
If you are given access to only one subsite, you see the navigation of the main site

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-subsites#268]
Steps to reproduce:

1. Create a user 
2. Switch to a subsite, and create a group with admin access to only one subsite
3. Try to log in as user created in step 1.

**Comment by dhensby** [comment]
version of SS and Subsites please

**Comment by torleif** [comment]
"silverstripe/cms": "3.4.1",
"silverstripe/framework": "3.4.1",
"silverstripe/subsites": "1.3.0",

**Comment by dhensby** [comment]
thanks

**Comment by robbieaverill** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
