### ISSUE TITLE
Permission Problem with SilverStripe Version 3.5+

### ISSUE THREAD

**Issue by Oliver996** [silverstripe/silverstripe-subsites#272]
When you create a new group or edit a group in security and you add the permission "Access to all CMS sections" the Users in this group can't publish, unpublish or delete pages. They also can only create pages on the top level. Only custom page classes that I created and where I overwrite the "canCreate" function, I can create anywhere and not only on top level. But I still can't publish, unpublish or delete these pages.

**Comment by dhensby** [comment]
What are your permission settings in the `Settings` area of the CMS?

**Comment by Oliver996** [comment]
In the moment I have all Options activated, except "full administrative rights" and "access to all CMS sections". But also in other configurations of the permission it still breaks when I add the "access to all CMS" permission.
I have tested it on my installation with extra permission options and also on a clean installation with only the subsite module. And in both options it breaks when i add "access to all CMS sections".

**Comment by RaBiw** [comment]
I have the same problem with the subsite module integrated in my 3.5.3 Project. Any solutions yet?

**Comment by Exeldur** [comment]
Push +1. When i use the subsite module in a 3.5.x installation, i have the same problem. Does anyone have a solution? It's very frustrating...

**Comment by robbieaverill** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
