### ISSUE TITLE
Circular dependency, dev-master with SS alpha6 

### ISSUE THREAD

**Issue by PixelDog** [silverstripe/silverstripe-subsites#274]
Trying out dev-master with alpha6 and:

PHP Fatal error:  Uncaught exception 'MJS\\TopSort\\CircularDependencyException' with message 'Circular dependency found: modelascontrollerroutes->subsiteconfig->modelascontrollerroutes' in /Applications/mampstack-5.6.30-2/apache2/htdocs/zsites/vendor/marcj/topsort/src/CircularDependencyException.php:34\nStack trace:\n#0 /Applications/mampstack-5.6.30-2/apache2/htdocs/zsites/vendor/marcj/topsort/src/Implementations/BaseImplementation.php(57): MJS\\TopSort\\CircularDependencyException::create(Array)\n#1 /Applications/mampstack-5.6.30-2/apache2/htdocs/zsites/vendor/marcj/topsort/src/Implementations/ArraySort.php(63): MJS\\TopSort\\Implementations\\BaseImplementation->throwCircularExceptionIfNeeded(Object(stdClass), Array)\n#2 /Applications/mampstack-5.6.30-2/apache2/htdocs/zsites/vendor/marcj/topsort/src/Implementations/ArraySort.php(75): MJS\\TopSort\\Implementations\\ArraySort->visit(Object(stdClass), Array)\n#3 /Applications/mampstack-5.6.30-2/apache2/htdocs/zsites/vendor/marcj/topsort/src/Implementations/ArraySort.php(75): MJS\\TopSort\\Impl in /Applications/mampstack-5.6.30-2/apache2/htdocs/zsites/vendor/marcj/topsort/src/CircularDependencyException.php on line 34

**Comment by robbieaverill** [comment]
Hi @pixeldog, this module doesn't support SilverStripe 4 yet. PRs welcome!

**Comment by robbieaverill** [comment]
For reference- if you search this error message you'll find a few issues on the framework that show how to resolve it. Basically don't use `After: *` in YAML configuration, because the asterisk includes the module itself.
