### ISSUE TITLE
SiteTreeSubsites extension doesn't handle $action parameter for AbsoluteLink

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe/silverstripe-subsites#275]
https://github.com/silverstripe/silverstripe-subsites/blob/1.3/code/extensions/SiteTreeSubsites.php#L270

Calling $AbsoluteLink('myAction') in a template throws away "myAction" as it's ignored in the extension.

**Comment by dhensby** [comment]
PR?

**Comment by wernerkrauss** [comment]
@dhensby did a PR for SS4, could be backported to v3
