### ISSUE TITLE
Subsite virtual page renders without a template if pointing to an unpublished page

### ISSUE THREAD

**Issue by imprezio** [silverstripe/silverstripe-subsites#276]
If you create a subsite virtual page, and you point it to a normal page, and the normal page is unpublished, then the subsite virtual page renders without a template.

**Comment by robbieaverill** [comment]
Hi @imprezio - could you please provide your SS framework/CWP and subsites versions?

**Comment by robbieaverill** [comment]
@imprezio are any of these issues related to this for you? #235 #236 #185

**Comment by robbieaverill** [comment]
I can't reproduce this now using SilverStripe 4.4.x-dev with Subsites 2.3.x-dev, so closing
