### ISSUE TITLE
Allow subsite specific page types - Hide page types from the main site

### ISSUE THREAD

**Issue by michalkleiner** [silverstripe/silverstripe-subsites#280]
Let's have a main site with a couple of partially related subsites.

Subsites offer the functionality to disable certain page types for subsites, allowing to display only the relevant page types for the subsite.

The main site always has visibility of all page types. There's a way how to hide certain page types using the `hide_ancestor` config property, but that of course hides it from the subsites as well.

We can't also use `canCreate` method as that is checked too late and doesn't prevent the page type from appearing in the 'Add new' menus.

What would be the recommended way to go about this?

Subsites module specific extension to `CMSPageAddController` or `CMSMain` controllers or using Injector to replace the implementation offering a similar mechanism to 'Disallow page types?' which a Subsite can have defined?

**Comment by robbieaverill** [comment]
I haven't looked into this, but the hide_ancestor setting is configuration - it might be nice if you could have different sets of configuration for different subsites. That would mean you could hide a page in the main site and have it shown in subsites by virtue of that subsite's custom config taking precendence.

**Comment by robbieaverill** [comment]
@michalkleiner this seems like a question - feel free to ask on Stackoverflow/SS community Slack/SS forums
