### ISSUE TITLE
SilverStripe 4 Support (Ongoing)

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/silverstripe-subsites#281]
Work is underway to get Subsites running on SilverStripe 4, and this issue is meant as two things:

- A way to track progress publicly
- A warning not to try starting the upgrade independently!

Currently involved in the upgrade project: @wernerkrauss, @timkung, @cheddam

Key Milestones:

- [x] 100% of tests passing
- [x] Subsite management within CMS working
- [x] All routing and rendering working

Known issues:

- [x] Subsite toggle in CMS is based on LeftAndMain, breaks CMS currently
- [ ] Admin templates can't be overridden correctly, making it difficult to get the subsite dropdown rendering (see [this issue](https://github.com/silverstripe/silverstripe-framework/issues/6828))

[Werner's fork](https://github.com/wernerkrauss/silverstripe-subsites/tree/fix-ss-4-alpha-7) is currently where work is happening.

If you want to get involved, get in touch! I'll aim to keep this issue updated with progress.

**Comment by robbieaverill** [comment]
@Cheddam I think we should close this now that the master branch is SS4 compatible and it seems to be playing nice enough for now. Let's track individual issues going forwards on this repository :) Thanks for all your work!
