### ISSUE TITLE
Actions on SubsitesVirtualPage controller don't inherit from controller

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-subsites#284]
if you have an allowed action on a controller: 

```
	private static $allowed_actions = array(
		'foorbar'
	);
```

It will work on the page with the controller by navigating to /mypage/foobar. However if you navigate to myvirtualpage/foobar, a 404 will be returned. 

You can solve this by overriding the allowed actions on the SubsitesVirtualPage_Controller:

```
	public function allowedActions($limitToClass = null) {
		$extraactions = Config::inst()->get(
				get_class(ModelAsController::controller_for($this->CopyContentFrom())), 
				'allowed_actions', Config::UNINHERITED | Config::EXCLUDE_EXTRA_SOURCES
		);
		return array_merge(parent::allowedActions($limitToClass), $extraactions);
	}
```

**Comment by robbieaverill** [comment]
Thanks for the report @torleif - would you be keen to submit a pull request with some tests?

**Comment by dhensby** [comment]
@kinglozzer do you think your virtual page work would have addressed this?

**Comment by kinglozzer** [comment]
Probably, virtual pages now just use the “target” page’s controller directly (rather than pass things through a `VirtualPage_Controller`), so I would assume this should work as expected.

@wernerkrauss I know you’ve done work on SS4 compatibility recently, do you know if this functionality works?

**Comment by kinglozzer** [comment]
That would only apply to SS4 though, so I suppose we should fix this for 3.x if we can

**Comment by robbieaverill** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
