### ISSUE TITLE
Member::currentUser on Subsite

### ISSUE THREAD

**Issue by chromos33** [silverstripe/silverstripe-subsites#285]
Problem is I can't check Admin privilege after looking at a subsite Page.
When testing the Member::currentUserID() returns 0 even though I'm logged in in the Main site and
Subsite/admin leads to the adress magnling itself to Subsite/Mainsite/admin?SubsiteID=1....

Is there a way to check for logged in User on the subsite

**Comment by robbieaverill** [comment]
Hi @chromos33 - could you please provide your framework and subsites versions?

**Comment by chromos33** [comment]
Subsite 1.3 and Framework 3.3

**Comment by robbieaverill** [comment]
@chromos33 could you please provide some steps to reproduce this problem, including an example of how you've configured your subsites, whether you're talking about checking admin privileges on a page from the CMS or from the frontend, etc? Thanks!

**Comment by leochenftw** [comment]
This is still an issue. `Security::getCurrentUser()` under a subsite's domain is returning `NULL`. 

I understand the login is per domain per session, but when i try to https://subsite.url/admin, it will bounce to https://mainsite.url/admin, and the subsite user is never going to be granted with a logged-in state. 

If there is a way to work around this, please advice. Thank you!
