### ISSUE TITLE
SS 3.6.2 (unreleased) breaks Main Site tree

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-subsites#286]
This commit https://github.com/silverstripe/silverstripe-framework/commit/5b6a39e71a61fd595a913788c412b8e249611bff ([PR](https://github.com/silverstripe/silverstripe-framework/pull/7035)) is slated to make it in to SS3.6.2 and causes the main site tree to disappear (0 nodes), if the main site is a 'default' site, i.e. not created within the Subsites admin area (Subsite ID=0). The CMS page tree still works for other/regular subsites.

@dhensby @mfendeksilverstripe

**Comment by dhensby** [comment]
@jonom do you know what aspect of that commit breaks the main site?

**Comment by jonom** [comment]
No, I spent a couple of hours trying to work it out but didn't get too far. This module augments SQL so I wonder if something needs to be tweaked about how it augments the site tree request? I don't think the referenced commit is necessarily a breaking/non-bc change, the subsites module kind of hacks things up to accomplish it's goals so I wouldn't expect it to be super stable.

**Comment by dhensby** [comment]
OK - well we've reverted it from 3.6 but it will likely still be a problem in 3.x (3.7) so this needs looking into

**Comment by robbieaverill** [comment]
I haven't noticed this as a problem in SilverStripe 3.6.x so going to close it. Feel free to reopen it if I've missed something obvious :)

**Comment by jonom** [comment]
@robbieaverill, @dhensby [reverted this change in the 3.6 branch](https://github.com/silverstripe/silverstripe-framework/commit/7b6aad8a65be6273879287c81b3eeb309b877c76), so yes, you wouldn't notice it as a problem in 3.6.x 😄
