### ISSUE TITLE
Bootstrapping issue: InitStateMiddleware needs to catch DatabaseException

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-subsites#295]
See https://github.com/silverstripe/silverstripe-subsites/blob/master/code/Middleware/InitStateMiddleware.php#L18

As we are no longer using database_is_ready() we need a catch (DatabaseException) in all middlware to allow dev/build to pass.

**Comment by tractorcow** [comment]
cc @robbieaverill

**Comment by robbieaverill** [comment]
I've fixed this in #294 but could also implement a more robust solution

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-subsites/commit/65f85faff6ee0d8598828351e85bbf4dbabbed45
