### ISSUE TITLE
Update FileSubsites extension so it works with asset admin

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-subsites#296]
The changes to the asset admin area of SilverStripe 4 mean that the FileSubsites extension approach doesn't work in the way it used to in SS3.

We need to come up with a new approach to either filter files by the selected subsite, or add a selector to the file details to assign a subsite to it.

## Pull requests

- [ ] https://github.com/silverstripe/silverstripe-subsites/pull/334

**Comment by sminnee** [comment]
On the plus side, this will be a good test of the all the react extensibility work that was done a couple of months back :-)

**Comment by tractorcow** [comment]
It should work the same way... augmentSQL conditions should continue to work in asset-admin.

Just make sure that any CMS forms updates you apply are instead added to the AssetFormFactory instead. :)
