### ISSUE TITLE
SS4: ErrorPage generation throws error when SubsiteDomain includes port numer

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe/silverstripe-subsites#299]
On my local dev environment (Vagrant VM with port forwarding) I have a SubsiteDomain like "myproject:8080". Now on dev/build I get this error:

> [Warning] file_put_contents(/vagrant/www/assets/error-404-myproject-lokal:8080.html): failed to open stream: Protocol error

Easy to fix when applying `FileNameFilter` to `ErrorPageSubsite`, will create a PR for it

**Comment by robbieaverill** [comment]
@wernerkrauss thanks, this probably affects SS3 users too. Would you be able to fix against the SS3 version if so? We can merge it up for SS4 afterwards
