### ISSUE TITLE
Fix Behat build in Travis

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-subsites#323]
A while back a change in core meant the subsites Behat tests started failing, so we've added them to allowed failures.

We should revisit and ensure they're working.

**Comment by robbieaverill** [comment]
They're still broken, but there are a few examples in core now with working Behat builds on trusty and SS4, so we should update to match Travis configuration in those modules - see framework, cms, etc.

**Comment by robbieaverill** [comment]
Behat should be easier to implement in a stable way now that core is using chromedriver - see examples in the core modules

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-subsites/pull/363

**Comment by NightJar** [comment]
For some reason this has not auto-resolved with the merge of #363 
Is it closable?

**Comment by robbieaverill** [comment]
It doesn't unless you merge into master or merge up to master. Yep we can close it
