### ISSUE TITLE
[Feature Request] Subsite Specific Files

### ISSUE THREAD

**Issue by chromos33** [silverstripe/silverstripe-subsites#324]
Is it possible to Restrict Images/Files to each Subsite i.e. You can only access Images/Files from subsite A, from subsite A. So as i.e an admin user from Subsite A you can only set Files/Images in the uploadfield that actually "belong" to that Subsite.

**Comment by robbieaverill** [comment]
@chromos33 are you using SilverStripe 3 or 4?

**Comment by chromos33** [comment]
Silverstripe 3

**Comment by robbieaverill** [comment]
Have you tried applying the Subsite File extension?

**Comment by chromos33** [comment]
How blind am I? :D while it would be nice if you could limit main page file accessibility to subsites this is good enough
