### ISSUE TITLE
Settings Button not showing in admin menu for each subsite

### ISSUE THREAD

**Issue by daza1** [silverstripe/silverstripe-subsites#341]
Hi,

Using subsite module in ss4. 
Settings Button not showing in admin menu for each individual subsite.
I tried this in a _config yml file but didn't work -
```
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SilverStripe\Subsites\Extensions\SubsiteMenuExtension

```
Got help from https://silverstripe-users.slack.com channel. this works.
```
SilverStripe\SiteConfig\SiteConfigLeftAndMain:
  extensions:
    - SilverStripe\Subsites\Extensions\SubsiteMenuExtension
```

Needs to be **SiteConfigLeftAndMain**

Hope this helps.
Thanks.

**Comment by robbieaverill** [comment]
Hi @daza1, thanks for raising this issue.

The first example is required to allow you to have varying SiteConfig data between subsites. This needs to remain unchanged.

Your second example is correct, and is missing from `extensions.yml` at the moment. Also missing is a broken namespace reference to SubsiteAdmin:

```diff
-SilverStripe\Subsites\SubsiteAdmin:
+SilverStripe\Subsites\Admin\SubsiteAdmin:
   extensions:
     - SilverStripe\Subsites\Extensions\SubsiteMenuExtension
 

```

Would you be keen to make a pull request to fix these two issues?

**Comment by adrexia** [comment]
Just to add to this, it looks like the issue is that `CMSSettingsController` has changed to `CMSPageSettingsController` here: https://github.com/silverstripe/silverstripe-subsites/blob/master/_config/extensions.yml#L63  rather than being updated to `SiteConfigLeftAndMain`

I don't think `CMSPageSettingsController`  is required.

**Comment by robbieaverill** [comment]
Ah, good catch!

**Comment by daza1** [comment]
Thanks, best if you make the  pull request, I'm still learning.

**Comment by digitall-it** [comment]
This seems to happen also with the Campaigns tab.

**Comment by robbieaverill** [comment]
Yes probably. We haven't applied the subsite extension nor the menu extension to campaigns yet. Would you like to make a pull request to add it?

**Comment by digitall-it** [comment]
I'll try. That means campaigns should be aware of subsites and also add another extension to the SilverStripe\CMS\Controllers\CMSPagesController, like on #342, right?

**Comment by robbieaverill** [comment]
@tractorcow do you have any thoughts on applying subsites to ChangeSet (campaigns) ?
