### ISSUE TITLE
CMS menu items not visible when when user doesn't have 'access to all CMS sections' 

### ISSUE THREAD

**Issue by sandervanscheepen** [silverstripe/silverstripe-subsites#346]
When a user doesn't have 'Access to all CMS sections' rights but just access to a few modeladmins, the CMS doesn't render any menu items in the CMS (or pageload just fails with a 403 message).

It seems to come down to the part in LeftAndMainSubsites after the following comment:

"// Collect permissions - honour the LeftAndMain::required_permission_codes, current model requires
// us to check if the user satisfies ALL permissions. Code partly copied from LeftAndMain::canView."

The code in LeftAndMain::canView that is refered to changed in SS4. When, for testing purposes, I paste the code from the getRequiredPermissions method from LeftAndMain into LeftAndMainSubsites, everything seems to work as expected.

**Comment by robbieaverill** [comment]
Thanks for reporting. Would you like to make a pull request to fix this issue?

**Comment by raissanorth** [comment]
Hi @sandervanscheepen, thanks for reporting this. Could you please elaborate on what you mean by menu items?!

I tried to reproduce this with `subsites 2.1.1`, `cms 4.x-dev`, and framework `4.x-dev`; I made a user that has no permissions to see the files, jobs, reports and security section. These are - as expected - the only section that user cannot see.

Limited permissions user sees:



Default admin sees:
![image](https://user-images.githubusercontent.com/14869519/43290736-224316c6-9183-11e8-816c-bd1f104ee72b.png)

**Comment by robbieaverill** [comment]
Please feel free to reopen the issue if you're still experiencing it and can provide some clear steps to reproduce =) Thanks for reporting!
