### ISSUE TITLE
Subsite vs Localedomains

### ISSUE THREAD

**Issue by innomedia** [silverstripe/silverstripe-subsites#347]
Is there any way to set a default language per domain so you can have a separate domain per language without mixing up subsites and locale domains?

E.g.:
firstsite.com > Subsite 1 and language english
firstsite.de > Subsite 1 and language german
secondsite.com > Subsite 2 and language english
secondsite.de > Subsite 2 and language german

As far as i can see the only way is to have four subsites with only one language each.

**Comment by NightJar** [comment]
Hi @innomedia 
When raising feature requests (or an integration issue) like this, it's important to also report which version of the applicable modules you're using, and also tell us which translation module you're trying to integrate with (in the very least).
Are you able to supply this info please?

You should be able to get it easily if you have installed the site via `composer`, by using `composer show` - it will tell you all the packages it has installed, and at what versions.

**Comment by innomedia** [comment]
This is related to the latest version (master/1.4)

**Comment by NightJar** [comment]
@innomedia can you please use `composer show` so we can see the exact versions and combinations of modules you have installed? You can of course filter anything sensitive from the output :) We're only really interested in the `silverstripe` vendor modules.

1.4.0 is the latest stable version, compatible only with SilverStripe 3
`master` is the head of development, compatible only with SilverStripe 4

If you are using the master branch on a SilverStripe 3 installation then this is sure to fail.

**Comment by innomedia** [comment]
Dear @NightJar,
we are running on SilverStripe 3.6 and SubSites 1.4.0
Unfortunately there is nothing in the docs about languages and domains. Maybe the subsites module is not capable of linking langauges to domains inside of a single subsite. Maybe this is the wrong place to ask questions like these. I will try at the reopened SilverStripe Forums.

**Comment by NightJar** [comment]
OK, this is more relevant information :)
From this I infer that you are not using a language module.
To my knowledge Subsites only provides the subsite (ie. more than one `SiteConfig` model), not any particular language functionality. You might like to also install either [Translatable](https://github.com/silverstripe/silverstripe-translatable) or [Fluent](https://github.com/tractorcow/silverstripe-fluent/) - these may be more applicable to your use case.

**Comment by innomedia** [comment]
We have both - Subsites and Translatable. This works so far. But as mentioned in the first post, we aim at linking domains to translations. which means if you change the language of one subsite it shall switch the domain too. E.g. changing from german language to english language on one subiste it should change the domain from let's say www.domain.de to www.domain.com. Same should work for a second or third subiste with multiple languages too. As far as i can see, the only way to do so is to split the languages in to completely seperate subsites with only one language each (which is the subsites default language). But: this way linked pages across translation groups would be lost.
So maybe it could work if one would not set a any of the subsite domains as default and manage redirects and locale selection by custom code. Hope that is not too confusing.

**Comment by NightJar** [comment]
I'm not too familiar with either of the modules I'm afraid @innomedia - but from your description I would say that custom code is probably the best avenue to achieve this with certainty.
