### ISSUE TITLE
Cannot limit page types for a subsite

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-subsites#351]
**Affected versions**:

* 2.0.x-dev using SS 4.1.x-dev

Still passing on 2.0.x-dev using SS 4.0.x-dev

When I select a subsite in admin and disallow an Error Page for example, switch to that subsite and go to add a new page, the Error Page is still a valid option and I can still add it.

**Comment by wilr** [comment]
@NightJar @robbieaverill I'm reopening based on attached. In CWP 2.2, disallowed page types doesn't work again. Looks like the `SiteTreeSubsites::canCreate()` option for the page doesn't even get called.
<img width="1276" alt="Screen Shot 2019-03-26 at 9 17 09 PM" src="https://user-images.githubusercontent.com/101629/54981240-b6e80780-500c-11e9-9c74-d5ab15617e80.png">

**Comment by ScopeyNZ** [comment]
I had a brief look at this. It's caused by CMSMain caching of `canCreate` that doesn't factor in the current subsite (see `CMSMain::SiteTreeHints()`). It can be fixed with an extension (subclass) to `CMSMain` for `generateHintsCacheKey`.

**Comment by wilr** [comment]
Thanks @ScopeyNZ I see `generateHintsCacheKey` doesn't provide an extension hook so would the long term fix be to add a `extend` for that then have an extension in subsites?

**Comment by ScopeyNZ** [comment]
Yep. I think that'd be an appropriate addition to the `cms` module too. We might be able to add an `extend` as a patch change as we're fixing a bug (in a different module though) and we've used the "we aim to produce extensible code" line before.

**Comment by robbieaverill** [comment]
Fixed in #419
