### ISSUE TITLE
DB error when updating from old DB (2.3)

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe/silverstripe-subsites#356]
I just encountered this error while updating a really old site to latest Subsites in SS4.1:

> ERROR [Emergency]: Uncaught SilverStripe\ORM\Connect\DatabaseException: Couldn't run query:
> 
> SHOW FULL FIELDS IN "SilverStripe\Security\Group"
> 
> Table 'database.SilverStripe\Security\Group' doesn't exist

It's caused by `SilverStripe\Subsites\Extensions\GroupSubsites->requireDefaultRecords`

**Comment by robbieaverill** [comment]
Nice catch. Do you fancy making a pull request to fix it?

**Comment by robbieaverill** [comment]
Fix at #362
