### ISSUE TITLE
subsites and newsletter module

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-subsites#37]
From http://open.silverstripe.org/ticket/4690

At present, using trunks, you can not use the newsletter module and the subsite module. That is, the newsletter will not be separated by subsite or in other words, if you create a newsletter it will be accessible to ALL subsites.

I have written two classes to fix these. They are operational and seem to be working. If anyone (including SS) is interested in adding these in some form or other then let me know: nicolaas [at] sunnysideup.co.nz.

**Comment by robbieaverill** [comment]
Closing, feel free to reopen if this is still an issue (although this sounds like an issue for the newsletter module rather than subsites).
