### ISSUE TITLE
Problem finding Subdomain table on Windows

### ISSUE THREAD

**Issue by Rudston** [silverstripe/silverstripe-subsites#379]
Hello, I seem to have found a bug that affects Windows users. In the file /vendor/silverstripe/subsites/src/Model/Subsite.php the $domainTableName is assumed to be SubsiteDomain::class which is usually the case except for Windows users :) where lower case applies ...

Modifying the code as follows, enables the function getSubsiteIDForDomain() to deliver:

$domainTableName = $schema->tableName(SubsiteDomain::class);
            $domainTableNameWindows = strtolower($domainTableName);
            if (!in_array($domainTableName, DB::table_list()) && !in_array($domainTableNameWindows, DB::table_list())) {
                // Table hasn't been created yet. Might be a dev/build, skip.
                return 0;
            } 
Forgive me, if I have not followed some or other protocol - this is the first time I have submitted an issue :)

**Comment by dhensby** [comment]
Table names in Windows should not be lowercase. You need to set up My SQL on your environment to support casing of DB identifiers

**Comment by NightJar** [comment]
One doesn't need to alter MySQL settings, to my knowledge. I run windows and it works as expected, even with lower case table names (the default).

MySQL on Windows places tables created in lower case, true.
But it also _matches_ table names in queries as case insensitive.

Caveat: Not tested.
