### ISSUE TITLE
Duplicate tab names when creating a subsite

### ISSUE THREAD

**Issue by mak001** [silverstripe/silverstripe-subsites#390]
![subsite-1](https://user-images.githubusercontent.com/1750550/45515099-cee0f380-b76c-11e8-9e5f-22959a7bd88e.png)
![subsite-2](https://user-images.githubusercontent.com/1750550/45515100-cf798a00-b76c-11e8-8c8f-acc11f17cfef.png)

Caused by the main tab getting renamed and another tab being created with the title `Configuration`
https://github.com/silverstripe/silverstripe-subsites/blob/5b8a0dbf13af8b81a519e50de6afaf52eaaf6047/src/Model/Subsite.php#L733
https://github.com/silverstripe/silverstripe-subsites/blob/5b8a0dbf13af8b81a519e50de6afaf52eaaf6047/src/Forms/GridFieldSubsiteDetailFormItemRequest.php#L45

One of these should be renamed, or they should be merged to reduce confusion.

**Comment by robbieaverill** [comment]
Thanks, PR at https://github.com/silverstripe/silverstripe-subsites/pull/391
