### ISSUE TITLE
getIsAdmin() should not reference AdminRootController config directly

### ISSUE THREAD

**Issue by DorsetDigital** [silverstripe/silverstripe-subsites#394]
When determining whether a request is in the CMS, the middleware currently reads the `AdminRootController.url_base` config value directly.

https://github.com/silverstripe/silverstripe-subsites/blob/5b8a0dbf13af8b81a519e50de6afaf52eaaf6047/src/Middleware/InitStateMiddleware.php#L65

If the admin URL has been changed via `Director` rules, but the `url_base` option in `AdminRootController` hasn't also been set, the `getIsAdmin()` function will end up with the wrong URL.

`AdminRootController::admin_url()` is available which checks the `Director` rules before falling back to the config option.  Would this be a better method of checking the admin routes?

**Comment by robbieaverill** [comment]
Thanks for reporting. Yes, your suggestion sounds perfect. Would you mind making a PR?

**Comment by DorsetDigital** [comment]
Not a problem.  Should I do that against the 2.1 branch, or 2.0.x ?

**Comment by robbieaverill** [comment]
Whichever you like. 2.0 might be better and we can merge up

**Comment by robbieaverill** [comment]
Fixed with #395 thanks @DorsetDigital
