### ISSUE TITLE
Middleware should not expect an HTTPRequest

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-subsites#401]
SilverStripe boots itself by creating a request type, then running it through a series of middleware before finally processing.
One of these middlewares is supplied by Subsites when installed, and serves to check the request domain and match it to a subsite, altering the course of the request internally, as such.

The issue manifests when one requests the system to do something via the CLI - there is no clear way to request a particular subsite, nor does the middleware currently take into account the possibility of the database not being present

E.g. running `sake dev` before a `dev/build` will result in a fatal error.

**Comment by robbieaverill** [comment]
Can you wrap injector calls to get three request in `->has(HTTPRequest::class)` checks?

**Comment by NightJar** [comment]
I haven't looked into it at all yet, but I'll keep your suggestion in mind when I do :)
This issue is preventing a deployment that smoke tests an installation before doing a dev/build

**Comment by robbieaverill** [comment]
I can't reproduce this on CWP 2.2.0-rc1

**Comment by NightJar** [comment]
:thinking: Maybe it's something to do with _installing_ subsites.
Perhaps try:
- create a standard project (_without subsites_)
- test `sake dev`
- complete `sake dev/build`
- install subsites
- test `sake dev`

**Comment by robbieaverill** [comment]
I've just re-tested this with SilverStripe 4.4.x-dev and subsites 2.2.0, the steps above don't reproduce the error. Feel free to reopen if you can work out why this was happening for you =)
