### ISSUE TITLE
Change the way the active subsite is loaded in the CMS

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-subsites#410]
Currently the subsite open for editing are stored in the user's session. This has unintended side effects such as silently changing the subsite (related: #409) between edits - particularly when adding records in a `ModelAdmin`, but not limited to this.

These states can occur when a user has two tabs open and uses one for the main site and the other for a subsite (e.g. for cross-reference while editing)

It would be better to move the subsite state into a GET parameter or a request header, some such less silently mutable and global state handler.

**Comment by robbieaverill** [comment]
Closing as a duplicate of #314
