### ISSUE TITLE
Referencing a page in Subsite Virtual Page fails if you have to navigate to deeper sitetree level

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-subsites#412]
Steps to reproduce: 

1. create a new subsite virtual page

2. change to another subsite with a large number of pages 

3. attempt to link to a page where it triggers an ajax reload

This is what is displayed in the SubsitesTreeDropdownField:

![output2](https://user-images.githubusercontent.com/67215/56993051-8721b600-6bef-11e9-8f9c-0de617427e1e.PNG)

This is likely the same issue as #337, only this one only gets triggered when trying to load more json for the SubsitesTreeDropdownField.

The json url then returns a 302 redirect which redirects to the page the browser is trying to download the json from:

![output1](https://user-images.githubusercontent.com/67215/56993050-8721b600-6bef-11e9-94b3-10a8341e9682.PNG)

and in the console of the browser

![output3](https://user-images.githubusercontent.com/67215/56993052-87ba4c80-6bef-11e9-9784-e65aa379d062.PNG)

We have a temporary fix in place which forces any request with the GET parameter from the SubsitesTreeDropdownField to load the sitetree json, regardless of what subsite it's on. This is the code we use:

**config.yml**
```yml
SilverStripe\Admin\LeftAndMain:
  extensions:
    - OP\OPLeftAndMainSubsites
```

**OPLeftAndMainSubsites.php**
```php

<?php

namespace OP;
use SilverStripe\Subsites\Extensions\LeftAndMainSubsites;
use SilverStripe\CMS\Controllers\CMSPageEditController;
use SilverStripe\Control\Controller;
use SilverStripe\Core\Config\Config;

/**
 * 
 * if the user is attempting to load the SubsitesTreeDropdownField json, we force
 * the global subsite to avoid any 302 redirects
 *
 * @author torleifw
 */
class OPLeftAndMainSubsites extends LeftAndMainSubsites {
    
    public function onBeforeInit()
    {
        $request = Controller::curr()->getRequest();
        if($request->getVar('CopyContentFromID_SubsiteID') !== null) {
            Config::inst()->set(CMSPageEditController::class, 'treats_subsite_0_as_global', true);
        }
        return parent::onBeforeInit();
    }
}

```

This is not the best fix. ideally the fix would be in SubsiteMenuExtension, and not relying on checking GET variables to trigger not redirecting the browser to the subsite you want to load the json from.

**Comment by robbieaverill** [comment]
@torleif I'm not sure I can reproduce this issue. What do you define as "a large number of pages"?

**Comment by torleif** [comment]
@robbieaverill large enough to trigger an ajax update of the SubsitesTreeDropdownField

**Comment by robbieaverill** [comment]
Presumably this is related to what you set `TreeDropdownField.node_threshold_total` to?

**Comment by torleif** [comment]
This looks to be resolved with the new tree selector field - i tried reproducing it but it seems to be ok now.
