### ISSUE TITLE
Wildcard subdomain doesn't match www when strict matching is off

### ISSUE THREAD

**Issue by michalkleiner** [silverstripe/silverstripe-subsites#414]
Subsite domain configured as *.example.com fails to match www.example.com when the `strict_subdomain_matching` config is false.

**Comment by robbieaverill** [comment]
Would you mind taking a look at `testStrictSubdomainMatching` and seeing if you can provide a failing test case for this?

**Comment by robbieaverill** [comment]
Quick look into this via `testStrictSubdomainMatching`:

```php
$subsite1 = $this->createSubsiteWithDomains([
    'example.org' => true,
    'example.com' => false,
    '*.wildcard.com' => false, // boolean: isPrimary
]);
// ...
Config::modify()->set(Subsite::class, 'strict_subdomain_matching', false);
// ...
$this->assertEquals(
    0,
    Subsite::getSubsiteIDForDomain('www.wildcard.com'),
    'Doesn\'t match www prefix without strict check, even if a wildcard subdomain is in place'
);

// ...
Config::modify()->set(Subsite::class, 'strict_subdomain_matching', true);
// ...
$failed = false;
try {
    Subsite::getSubsiteIDForDomain('www.wildcard.com');
} catch (UnexpectedValueException $e) {
    $failed = true;
}
$this->assertTrue(
    $failed,
    'Fails on multiple matches with strict checking and wildcard vs. www'
);
```

While this is a little confusing to read, the first assertion indicates to me that what you're reporting is expected behaviour.

Do you agree with this @michalkleiner?

**Comment by michalkleiner** [comment]
Thanks for having a look @robbieaverill. Yep, I get that it does what it does now and it's expected by the code, but is it how it actually should work? It's really strange behaviour that "everything" doesn't match "something specific".

**Comment by robbieaverill** [comment]
cc @silverstripe/creative-commoners for feedback

**Comment by NightJar** [comment]
Readme except (paraphrased)

>- `example.com` and `www.example.com` are treated as the same domains.
>- to distinguish between them, set `Subsite::$strict_subdomain_matching = true`.
>- `strict_subdomain_matching` will _**not**_ affect wildcard (`*`) checks

https://github.com/silverstripe/silverstripe-subsites#strict-subdomain-matching

So with `strict_subdomain_matching` in the default configuration of `false`
- `'www.'` and `''` (or `^www\.` and `^$` in regex parlance) are equivalent
- `example.com` does not match `*.example.com`
- a.k.a.`^$` does _not_ match `^subdomain\.` (nor should it)
- thus `^www\.` does not match `subdomain\.`

This is poorly explained, but correct behaviour I would have to agree with the test.

**Comment by robbieaverill** [comment]
Thanks, closing as expected behaviour

**Comment by NightJar** [comment]
Perhaps the easiest way to think of this is:
`strict_subdomain_matching === false` => `www.` is stripped from the domain before any comparisons.

I would welcome a docs update though @michalkleiner :)

**Comment by michalkleiner** [comment]
@NightJar and my only problem is with 
> `example.com` does not match `*.example.com`

which I think has nothing to do with whether it does or doesn't starts with `www.` or these being treated as equal based on the config option.

Would that be a BC issue if that behaviour changed?

**Comment by NightJar** [comment]
I think there is a critical difference between those two though @michalkleiner 

Main domain vs _any subdomain_

If there is no subdomain, then I think it neither feasible nor reasonable for "a subdomain" do suddenly change meaning to "the main domain".

-----

I guess this is a critical difference between regex thinking (where `*` is "0 or more") and domain matching.

But even then, considering the (literal) `.` separating the `*` from the main domain, this doesn't work in a regex concept either, as the `.` separates main domain from subdomains, and is always present.

**Comment by michalkleiner** [comment]
Fair enough, appreciate the persistence. Let's keep it closed, I'll fork or extend when/as needed.

**Comment by NightJar** [comment]
The most succinct way to put it would be that:
Your proposed change would be to make a rule to search for "something", also match «nothing»

I can't think of a valid use case, but it sounds like you have one :)
Personally I think I'd try to find a way to work around the issue with some kind of e.g. middleware or injected service to alter the domain lookup (or mutate the request for the same reason), rather than a full fork. But if there are static references all over the show, then a fork is probably the best option. You're a good dev, I'm sure you'll figure it out :) Just remember to leave lots of comments and good commit messages so it can be seen _why_ your adaptations exist when it comes to support time!
