### ISSUE TITLE
When basic auth is enabled, subsite filter behaves incorrectly

### ISSUE THREAD

**Issue by scott1702** [silverstripe/silverstripe-subsites#429]
When enabling basic auth on a site, the subsite filter appears to behave incorrectly. e.g when accessing the homepage via the domain for Subsite1, some (not all) data appears from the HomePage from Subsite2. Also when accessing the CMS pages from both subsites are appearing in the SiteTree.

**Comment by robbieaverill** [comment]
Impact medium because this happens with basic auth enabled, which is usually only for test environments
