### ISSUE TITLE
Cannot duplicate page "Column 'URLSegment' in where clause is ambiguous"

### ISSUE THREAD

**Issue by cjsewell** [silverstripe/silverstripe-subsites#450]
When trying to duplicate certain pages, this SiteTreeSubsites extension throws the error  `Column 'URLSegment' in where clause is ambiguous`

While unable to identify the exact cause, as this only occurs on "some" pages, I assume its something to do with Fluent as well.

Converting `DataObject::get_one` to `SiteTree::get()->filter` seems to fix it

**Comment by NightJar** [comment]
Thanks for posting the fix too! :)
