### ISSUE TITLE
File uploaded to subsite is viewable to different subsite

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-subsites#453]
framework 4.x-dev 09aba35
subsites 2.x-dev fd10b86

I selected Subsite A

I uploaded file to 2 different locations:
- root folder
- subfolder that belong to main site

I then switched to Subsite B

I could still see the file, when I expected to no longer be able to see it

**Comment by michalkleiner** [comment]
Is that a bug though? It's a fair and reasonable assumption, but the module doesn't mention anywhere that it fully isolates all aspects of the CMS in terms of handling content and assets.

In the docs, there is a suggestion to put files in different/dedicated folders (https://github.com/silverstripe/silverstripe-subsites/blob/2/docs/en/userguide/set_up.md#assets), how sweet :)

**Comment by emteknetnz** [comment]
OK, this is basically my own misunderstanding.

Yes, as the docs say, assign the subsite at the folder level, not the file level.  This works as expected.

This is reasonable and being able to assign a subsite owner for for individual files is a feature that we probably don't even want as it would present extra complexity to cms authors.

I'll close this one
