### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by thomas2312** [silverstripe/silverstripe-subsites#465]
I run into the following error after installing silverstripe subsites with
`composer require silverstripe/subsites`

![error](https://user-images.githubusercontent.com/15725363/119613603-8fb03f00-bdfd-11eb-8341-59be5b47df67.PNG)

So /dev/build is not possible.

**Comment by maxime-rainville** [comment]
Can you provide us a full stack trace so we can see what his triggering the query?

**Comment by thomas2312** [comment]
I installed the plugin and now it is working.
