### ISSUE TITLE
(Feature Request) Template methods for disabling subsite filter

### ISSUE THREAD

**Issue by davejtoews** [silverstripe/silverstripe-subsites#474]
I'm able to disable subsite filters in a template by doing the following.

```
    $Subsite.disable_subsite_filter
    <% loop $Items %>
        <div> ... </div>
    <% end_loop %>
    $Subsite.disable_subsite_filter(0)
```

But passing a zero gets evaluated as a falsy string `"0"` rather than a true boolean value. This works but it doesn't seem particularly clean. Might be better to just have two template global methods `DisableSubsiteFilter()` and `EnableSubsiteFilter()`?

Or alternately for the use case I'm encountering it might be handy to opt a particular object relationship out of Subsite filtering altogether. I'm having to disable subsite filtering both on the CMS fields and in the template.

**Comment by michalkleiner** [comment]
You can create a class implementing `TemplateGlobalProvider` interface and add the methods there. Possibly the `Subsite` class itself can implement that interface and expose the mechanism for templates. Happy to look at a PR.

**Comment by GuySartorelli** [comment]
The problem described in the issue is ultimately that `0` in the template was interpreted as `"0"` - this is no longer the case in CMS 5. What's more you can pass real booleans now.
