### ISSUE TITLE
4.12 regression: "Copy to subsite" button shows in compare mode

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-subsites#495]
![image](https://user-images.githubusercontent.com/1168676/204721578-e1d2a9d6-6c2d-4bd4-a844-436aba20b365.png)

## Acceptance criteria
- [x] Copy to subsite button is not present in the compare view

## PRs
- https://github.com/silverstripe/silverstripe-subsites/pull/496

**Comment by GuySartorelli** [comment]
PR merged
