### ISSUE TITLE
CMS 5 - Setting a MAILER_DSN causes a circular dependency

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-subsites#506]
If you have have a MAILER_DSN set in .env, a circular dependency happens on flush=1

PHP Fatal error:  Uncaught MJS\TopSort\CircularDependencyException: Circular dependency found: modelascontrollercatchallroute->subsiteconfig->mailer-dsn-env->subsiteconfig in /var/www/vendor/marcj/topsort/src/CircularDependencyException.php:34

This happens in because of the new [mailer config](https://github.com/silverstripe/silverstripe-framework/blob/5/_config/mailer.yml#L21) which uses an After: '*'

### PRs
- https://github.com/silverstripe/silverstripe-subsites/pull/505

**Comment by emteknetnz** [comment]
I've tested this in sink, seems that only subsites has this issue, though there's a few others with that have After: `<module>/*` config
- cms/_config/version.yml
- cwp/_config/config.yml
- gridfieldqueiedexport/_config/config.yml

**Comment by GuySartorelli** [comment]
Seems strange that other things aren't having the problem - but it doesn't seem that subsites needed that anyway so I have no problem with the solution you've come to.

PR is merged.
