### ISSUE TITLE
Subsites + Fluent: Config setting not working

### ISSUE THREAD

**Issue by MLindenhofer** [silverstripe/silverstripe-subsites#509]
Hi,

According to the documentation (https://github.com/silverstripe/silverstripe-subsites#using-subsites-in-combination-with-fluent) it's possible to ignore the subsites locale and force using the FluentState locale instead but it seems it does not work anymore. We have the setting in our yml-file but it's ignored and the subsite still uses the locale from the subsite-settings.

Maybe you should update the documentation if it's really ended working :). 

 For our project I've used this workaround in PageController's init()-function:

`            if ($this->dataRecord->SubsiteID !== 0){
                i18n::set_locale(FluentState::singleton()->getLocale());
            }
`

Best regards

**Comment by maxime-rainville** [comment]
Can you clarify what version of Fluent you are using? 

Honestly, this is not a set up we run very often in our own project. I have no idea if what's stated in the doc is even true. If you do find a way to make it work, please report your finding here and/or open a PR to update the doc.

**Comment by MLindenhofer** [comment]
I think the fluent version is not cause of the problem (in our project it was Fluent 5.1.1 ), the code-part where the old yml-config-var seems not to be available anymore. Searched for it. Nothing found. 

Did my very first PR with the doc update, to help other developers with the same problem.
