### ISSUE TITLE
Incorrect template shown when user doesn’t have CMS access (specifically when the subsites module is installed)

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-subsites#529]
Related issue https://github.com/silverstripe/silverstripe-admin/issues/1443

Due to permissions failure being thrown with Security::permissionFailure($this->owner), incorrect template is applied and a user with no access can see the admin layout

I think this is probably more a framework level fix, but raising the issue here as well

PR
---

https://github.com/silverstripe/silverstripe-subsites/pull/533

**Comment by GuySartorelli** [comment]
Please provide more information, such as a clear description of exactly what behaviour is observed (what template is used, why is it incorrect, what template _should_ be used, etc) - and some reproduction steps (I'm assuming simply installing subsites without any configuration isn't enough to reproduce this)

**Comment by lekoala** [comment]
@GuySartorelli this is the same issue as the related issue : a user without access to the cms see the admin layout, but he should see the regular

i think installing the subsite module is enough the reproduce the issue. I've just tried on a fresh project, here it is:
- install ss5
- install subsite module
- create a demo user with no admin rights
- login with it
- go to /admin
- see a forever loading admin logo and js issues

<img width="648" alt="image" src="https://github.com/silverstripe/silverstripe-subsites/assets/250762/d21fd935-c1bc-4f9e-83bf-e279785c233a">

on ss4, you get the admin layout like so, even though it doesn't have admin access

<img width="520" alt="image" src="https://github.com/silverstripe/silverstripe-subsites/assets/250762/e49fd144-788e-48a3-b0c7-e7ea68b72587">

this can be fixed by replacing

https://github.com/silverstripe/silverstripe-admin/blob/971046c5219afcb295bead52830395cc3fe02337/code/LeftAndMain.php#L606

by a simple         if (!$this->canView()) {

i'm not raising this as an admin issue because it seems intentional to let modules send their own kind of redirect. I'm not sure that's wise and i think it's better to enforce at admin module level the fact that you cannot see the admin layout when you don't have the admin rights, rather than hoping that each module throw permission errors correctly.

**Comment by GuySartorelli** [comment]
The problem with `!$this->canView()` is that they might not be allowed to view the _current_ controller's actions, but maybe they're allowed to view other areas of the CMS and therefore should be given a CMS context for the error.
In any case thank you for the extra context!

**Comment by lekoala** [comment]
@GuySartorelli yes, you are right. in that case, it's possible to replace the canView by a !Permission::check('CMS_ACCESS')

**Comment by lekoala** [comment]
@GuySartorelli just revisited this issue for ss5, and the fix seems super easy: just let leftandmain do its job :-) see related pr here 
https://github.com/silverstripe/silverstripe-subsites/pull/533

**Comment by GuySartorelli** [comment]
Thank you for that @lekoala! That'll be autotagged by github actions.
