### ISSUE TITLE
CMSProfileController required_permission_codes breaks with subsites

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-subsites#535]
https://github.com/silverstripe/silverstripe-admin/pull/1027 caused failures when subsites was installed on the recipe-kitchen sink build here https://github.com/silverstripe/recipe-kitchen-sink/actions/runs/5892574918/job/15998642199

There was some [initial investigation](https://github.com/silverstripe/silverstripe-admin/pull/1555#issuecomment-1689037248) done that there's some additional work to be done on the subsites module to get it compatible

## PRs
- https://github.com/silverstripe/silverstripe-subsites/pull/536

**Comment by GuySartorelli** [comment]
Merged PR
