### ISSUE TITLE
Revert pull-request

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-subsites#538]
https://github.com/silverstripe/silverstripe-subsites/pull/490 was merged, though likely the green CI build was over a year old at time of merging.

The merge commit was red https://github.com/silverstripe/silverstripe-subsites/actions/runs/6044881143/job/16404112238 so the PR shouldn't have been merged in its current state. I tried rerunning to broken behat builds a couple of times though they remained red.

Checking out the commit on the 2.8 directly before the merge conflict fixed the behat test on my local

## PRs
- https://github.com/silverstripe/silverstripe-subsites/pull/539

**Comment by GuySartorelli** [comment]
PR merged and related issues reopened.
