### ISSUE TITLE
TODO: LeftAndMain_Subsites.getChangeTrackerOptions() - Investigate should we still address some edge cases with the Entwine API extension

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-subsites#541]
## Description
LeftAndMain_Subsites.getChangeTrackerOptions(). We should conduct an investigation to determine whether there are any remaining edge cases that need to be addressed with the Entwine API extension. [See](https://github.com/silverstripe/silverstripe-subsites/blob/86f01d20bb3c3a3a9aeb25058ae842b2fa20c6f2/client/src/js/LeftAndMain_Subsites.js#L65)

> There's a couple of edge cases that aren't obvious that come from ChangeTrackerOptions being an object, and might need an Entwine API extension to fix nicely.

See issue for more details: https://github.com/silverstripe/silverstripe-subsites/pull/125

**Comment by GuySartorelli** [comment]
Gonna close this one - changetracker and the subsites selector don't seem to be conflicting at all.
