### ISSUE TITLE
TODO: SubsiteDomain::getSubstitutedDomain() - Refactor domains into separate wildcards / primary domains

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-subsites#543]
## Description
SubsiteDomain::getSubstitutedDomain() - Refactor domains into separate wildcards / primary domains.

If follow logic of existing comments, 
```
- @property string $Domain domain name of this subsite. Can include wildcards.
- If there are wildcards in the primary domain (not recommended), make some educated guesses about what to replace them with:
```
We are looking `*` wildcards in some domains like `test.*`(first-level subdomains - `tes.com`) in the `getSubstitutedDomain` method, so I assume, that the main idea here to process wildcards for second-level subdomains, currently we do it like this, [see here](https://github.com/silverstripe/silverstripe-subsites/blob/86f01d20bb3c3a3a9aeb25058ae842b2fa20c6f2/src/Model/SubsiteDomain.php#L197) or any other ways provided wildcards,  something like `test.*.*` (test.test.com) or `*.test.*` (new.test.com). 

See:
https://github.com/silverstripe/silverstripe-subsites/blob/86f01d20bb3c3a3a9aeb25058ae842b2fa20c6f2/src/Model/SubsiteDomain.php#L183

**Comment by GuySartorelli** [comment]
@sabina-talipova Can you please provide more context, or close it if you don't have any additional context? It's not clear what is actually meant to happen for this one.

**Comment by sabina-talipova** [comment]
I've updated ticket. If you think that we shouldn't spend time on it. We can close it.

**Comment by GuySartorelli** [comment]
I don't think this is worth spending time on for now. If someone finds that this is a signigicant blocker for their use case they can provide additional context and we can reconsider.
