### ISSUE TITLE
TODO: Future enchantment for GridFieldSubsiteDetailFormItemRequest::ItemEditForm

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-subsites#544]
## Description

> @todo In the future, we will probably need to come up with a tigher object representing a partially  controller with gaps for extra functionality.  This, for example, would be a better way Security/login put its log-in form inside a UI specified elsewhere.

See:
https://github.com/silverstripe/silverstripe-subsites/blob/86f01d20bb3c3a3a9aeb25058ae842b2fa20c6f2/src/Forms/GridFieldSubsiteDetailFormItemRequest.php#L21

**Comment by GuySartorelli** [comment]
Gonna close this one. Sounds like it was a thought about how controller endpoints could be refactored, which we're already doing separately.
