### ISSUE TITLE
SiteTreeSubsites potentially inserts CopyToSubsiteID multiple times

### ISSUE THREAD

**Issue by sephyhe** [silverstripe/silverstripe-subsites#561]
### Module version(s) affected

^3.0

### Description

In the file - SiteTreeSubsites.php, the function `updateCMSFields` inserts SubsiteOperations with `CopyToSubsiteID`, `CopyToSubsiteWithChildren` and form action `copytosubsite`.
If there is a new page extended from Page and contains code `$this->extend('updateCMSFields', $fields);`
```
class ParentPage extends Page
{
    private static $table_name = 'ParentPage';

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();
        //Some changes
        ...

        $this->extend('updateCMSFields', $fields);
        return $fields;
    }
}
```

And all the other pages extended from ParentPage will get an issue:
```[Emergency] Uncaught RuntimeException: SilverStripe\Forms\{closure}() I noticed that a field called 'CopyToSubsiteID' appears twice```

Because the code here(https://github.com/silverstripe/silverstripe-subsites/blob/0fe63e92bd9a360471880bf4849f18de612aa0c1/src/Extensions/SiteTreeSubsites.php#L125) try to insert SubsiteOperations more than one time.

Therefore, it will be good to check if the fields are exiting or not before inserting them.

### How to reproduce

```
class ParentPage extends Page
{
    private static $table_name = 'ParentPage';

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();
        //Some changes
        ...

        $this->extend('updateCMSFields', $fields);
        return $fields;
    }
}
```

```
class ChildPage extends ParentPage
{
     private static $table_name = 'ChildPage';

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();
        // Error will happen at this page
        ...
        return $fields;
    }
}
```

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by GuySartorelli** [comment]
This is not a bug with subsites, it is a problem with how `$this->extend()` is being used.
If your subclass and parent class both call `$this->extend('updateCMSFields')` then it is expected that the same method will be called twice, and all of its code will be executed twice.

I recommend that instead you use `beforeUpdateCMSFields()` in your page subclasses.
For an example of this, see [BaseElement::getCMSFields()](https://github.com/silverstripe/silverstripe-elemental/blob/cfa66b966cec04ffc2cef0f08386691b5d54e121/src/Models/BaseElement.php#L349) and [ElementContent::getCMSFields()](https://github.com/silverstripe/silverstripe-elemental/blob/cfa66b966cec04ffc2cef0f08386691b5d54e121/src/Models/ElementContent.php#L35C16-L35C37) in `dnadesign/silverstripe-elemental`.

With this setup, the extension hook only gets called once - with the examples linked above, it gets called by `DataObject::getCMSFields()`.
