### ISSUE TITLE
Middleware should not make table check on each request

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-subsites#563]
### Module version(s) affected

3.x

### Description

Currently, the middleware make a table check on each request. While not super expensive, it feels that this is really unecessary

![image](https://github.com/silverstripe/silverstripe-subsites/assets/250762/343f04b5-b663-4a9f-938c-05cedb2a59be)

Related issues:

https://github.com/silverstripe/silverstripe-framework/issues/11181
https://github.com/tractorcow-farm/silverstripe-fluent/issues/828

### How to reproduce

Install debugbar
Install subsite module
Check the queries:  a SHOW TABLES LIKE 'SubsiteDomain' happen in each query

### Possible Solution

Don't make the check except on dev/build:
https://github.com/tractorcow-farm/silverstripe-fluent/pull/831

Rely on the cached ClassInfo::hasTable instead which will get even better in the future
https://github.com/silverstripe/silverstripe-framework/pull/11183

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## PRs
- https://github.com/silverstripe/silverstripe-subsites/pull/564

**Comment by GuySartorelli** [comment]
Pr is merged
