### ISSUE TITLE
Cannot view draft versions of subsite pages.

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-subsites#6]
Copied from http://open.silverstripe.org/ticket/4366

When editing pages in the CMS for a subsite, viewing the draft page returns an error page.

Warning: Invalid argument supplied for foreach() in /..../Debug.php on line 557

Fatal error: Cannot use object of type SQLFormatter as array in /..../Debug.php on line 531

Also on that page there is this which is just a snipit but has relevant info. Notice the "AND SubsiteID= )" bit.

SiteTree?.ID WHERE (ParentID = 0 AND SubsiteID= ) AND (SiteTree?.SubsiteID IN (3)) AND (SiteTree?`.SubsiteID IN (3)) ORDER BY Sort You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')

**Comment by robbieaverill** [comment]
Closing, if this is still a problem feel free to reopen
