### ISSUE TITLE
View "All Pages, Including Deleted" Broken

### ISSUE THREAD

**Issue by tazzydemon** [silverstripe/silverstripe-subsites#62]
I have been trying to track this one for days but if the subsite module is installed and one tries to use

View "All Pages, Including Deleted" 

then no pages are returned. I'm pretty sure its somewhere around getChildrenAsUL() in Heirarchy.php and getSiteTreeFor() in LeftAndMain.php. It might also be an incompatibilty due to incorrect or no extension of Versioned::get_including_deleted()

The augmentsql portion of Version has a complex codeset for the "latest_versions" case. If I alter  get_including_deleted() to "all_versions" then data is returned to the sitetree list - I think Im getting close.

If I see any more print_r() I will go nuts!

**Comment by robbieaverill** [comment]
Can't reproduce any more (SilverStripe 3.6.0). Feel free to reopen if this is still affecting you on more recent versions!
