### ISSUE TITLE
Subsites VirtualPage cannot perform any actions

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-subsites#7]
Copied from http://open.silverstripe.org/ticket/5727

I had a Main Site with a forum and a UserDefinedForm. The forum is the default installed by the forum module, while the UserDefinedForm was just a textbox and a Submit button.

I created two Subsites VirtualPages under the Subsite and pointed one to the forum and the other to the UserDefinedForm.

I navigated to the subsite page of the forum and clicked "Start a new topic". The following error was displayed: The action 'starttopic' does not exist in class !SubsitesVirtualPage_Controller. The URL was  http://site1.localhost/silverstripe/forums/general-discussion/starttopic

I navigated to the subsite page of the UserDefinedForm. I then entered a value in the textbox and clicked "Submit". The following error was displayed: The action 'Form' does not exist in class !SubsitesVirtualPage_Controller. The URL was  http://site1.localhost/silverstripe/test-userdefinedform/Form

Note that the forum and UserDefinedForm both work in the Main Site.

---

I also got another error by doing the following:
In the Main Site, create a new thread in the forum.
In the subsite, navigate to the forum's page. The new thread is displayed in the list of threads.
Click to view the new thread.
The error "The requested page could not be found." is displayed. The URL is  http://site1.localhost/silverstripe/show/1

**Comment by robbieaverill** [comment]
Looks fixed in the CMS issue linked, and the subsequent CMS issues linked from there
