### ISSUE TITLE
SubsiteID wrong in SiteTree[_Live] upon Save or Save and Publish

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-subsites#8]
Copied from http://open.silverstripe.org/ticket/3293

We've been using the Subsite module which has a bug where when you save the new page it frequently places the default Subsite 1 into the subsite field of the SiteTree? and SiteTree_Live tables. AJ nor we know how to fix this off the top and it happens rather frequently and requires an SQL modification for new pages on a daily basis. Sometimes perhaps if you flip the subsites back and forth a few times it may work okay, but it is very hit or miss.

Please advise as we need a fix for this rather quickly as the end users are having some issues with proper and timely deployment of new content and thus this is a serious issue.

**Comment by robbieaverill** [comment]
Closing, feel free to reopen if this is still an issue
