### ISSUE TITLE
not possible to create a folder for all subsites

### ISSUE THREAD

**Issue by cloph** [silverstripe/silverstripe-subsites#80]
in 3.1, with subsite module installed, asset-admin doesn't allow to create a folder for all subsites.

Only a single subsite can be chosen, and files added to that folder are only available for selection for that single subsite.

Having a "shared" option or a list of subsites where the files should be available would be more desireable.

**Comment by robbieaverill** [comment]
I'm going to close this as it's old now. If this is still affecting anybody please feel free to reopen the issue.
