### ISSUE TITLE
make switching possible without expanding left-hand module selection

### ISSUE THREAD

**Issue by cloph** [silverstripe/silverstripe-subsites#81]
in SilverStripe 3.1, the subsite selection dropdown is in the left-hand area, below the user's name.
When clicking the dropdown to switch subsites, the left-hand pane is expanded and has to be collapsed manually.

**Comment by robbieaverill** [comment]
I'm going to close this due to inactivity. If this is still an issue with SilverStripe 3.5 or newer, and more recent versions of subsites, please feel free to reopen 😃  Thanks for reporting!
