### ISSUE TITLE
GroupSubsites class does not select groups correctly

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-subsites#9]
Copied from http://open.silverstripe.org/ticket/4707

GroupSubsites? lets you select what subsite a group is for. However, if you are logged into a subsite, you end up not being able to select the right subsite, resulting in a "global" group being created that can not be deleted anymore.

We are running subsites/trunk.

Attached is how I HACKED it: http://open.silverstripe.org/attachment/ticket/4707/GroupSubsitesHack.patch

**Comment by robbieaverill** [comment]
Closing, if anyone experiences this issue still please feel free to open a new issue
