### ISSUE TITLE
Subsite error pages not displayed

### ISSUE THREAD

**Issue by frankmullenger** [silverstripe/silverstripe-subsites#98]
Error pages for subsites are generated with unique file names:
https://github.com/silverstripe/silverstripe-subsites/blob/master/code/extensions/ErrorPageSubsite.php#L31

However, these error pages do not seem to be used. There are entries in the .htaccess  for using custom error pages:
https://github.com/silverstripe/silverstripe-installer/blob/3.1/.htaccess#L20

But these do not cover the subsite error pages and it doesn't seem like you can set custom error pages for different subsites in .htaccess.
### To Replicate

Create a 403 error page for a subsite
Try and access a forbidden resource using the subsite domain
### Solution

Not sure what the best approach is? Is there a solution to this that would not require using ErrorDocument in a virtual hosts directive? Possibly a separate controller for ErrorDocument handling for subsites?

**Comment by robbieaverill** [comment]
I can't reproduce this on SilverStripe 4.4 with Subsites 2.3.x-dev. Error pages created in subsites are correctly shown in those subsites for me.
